spring:
  application:
    name: user-center
    # mysql??
  datasource: # 数据库的相关配置
    username: root
    password: "1024"
    url: jdbc:mysql://localhost:3306/starboll_one?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8 #serverTimezone=Asia/Shanghai ??????????
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## 设置session失效时间为一天
  session:
    timeout: 86400
  # mybatis-plus??
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 配置的日志，可以看到具体sql语句的执行
    map-underscore-to-camel-case: true     #解决，查询返回结果含null没有对应字段值问题,解决驼峰式命名 (字段名：s_name 《==》 属性名：sName)
  #    useDeprecatedExecutor: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 8081
  # 会在所有的controller路径上之前加上一个'/api'前缀
  servlet:
    context-path: /api